package io.github.divinegenesis.communicator.config

import org.spongepowered.configurate.objectmapping.ConfigSerializable
import org.spongepowered.configurate.objectmapping.meta.Comment
import org.spongepowered.configurate.objectmapping.meta.Setting

@ConfigSerializable
class BotConfig {

    val mainConfiguration = MainConfiguration()

    val databaseConfig = DatabaseConfig()

    val authorizationConfig = AuthorizationConfig()

    @Setting("Authorized-Bots")
    @Comment("This should be the bots UserID, for example Dyno's UserID is \"155149108183695360\"")
    val authorizedBotList = listOf("")
}

@ConfigSerializable
class MainConfiguration {

    @Setting("GuildID")
    val guildID = ""

    @Setting("OwnerID")
    val ownerID = ""

    val debugChannel = ""

    val botToken = ""

}

@ConfigSerializable
class AuthorizationConfig {

    @Setting("EmoteID")
    val emoteID = ""

    @Setting("ChannelID")
    @Comment("The channel ID of where to listen for the emote")
    val channelID = ""

    @Setting("Verification-ChannelID")
    @Comment("The channel id where verification is sent to")
    val verificationID = ""

    @Setting("MessageID")
    @Comment("The message ID, used for removing a users emote if they leave")
    val messageID = ""

    val questions: List<String> = listOf(
        """
        *First of all: Thank you for being so kind to take the time for us, your dedication will not go unnoticed!*
        **1. Can you try to explain our Rule and Etiquette in your own words?**
        *The Rule stands for having to use your common sense at best of your ability & the Etiquette expects of you to do your best at being a good person.*
    """.trimIndent(),
        """
        **2. Have you checked and do you agree with the Fact?**
        *Agreeing to this fact means you understand and accept that other users may for example: create content by using the activity that is generated by you.*
    """.trimIndent(),
        "**3. What is the password?**"
    )

}

@ConfigSerializable
class DatabaseConfig {

    @Setting("Database-Host")
    val host = "localhost"

    @Setting("Database-Port")
    val port = "3306"

    @Setting("Database-Name")
    val dbName = ""

    @Setting("Username")
    val dbUsername = ""

    @Setting("Password")
    val dbPassword = ""
}